# Enable GPIO Expander support
CONFIG_GPIO_TCA6424A=y

# Enable EEPROM support
CONFIG_EEPROM=y
CONFIG_EEPROM_AT24=y

# 1. Base I2C (Usually defaults to 40 or 50)
CONFIG_I2C_INIT_PRIORITY=50

# 2. The Mux Root (The physical chip)
CONFIG_I2C_TCA954X_ROOT_INIT_PRIO=60

# 3. The Mux Channels (The logical paths)
# IMPORTANT: These must be ready before the expander tries to talk!
CONFIG_I2C_TCA954X_CHANNEL_INIT_PRIO=70

# 4. The I/O Expander
# It must be HIGHER than the channel priority
CONFIG_GPIO_TCA6424A_INIT_PRIORITY=80

# 5. SPI Controller
CONFIG_SPI_INIT_PRIORITY=85

# 6. SPI NOR Flash
# Push this to the very end of the boot sequence (APPLICATION level starts at 90+)
CONFIG_SPI_NOR_INIT_PRIORITY=99

# WS2812B LED strip on LED_STATUS
CONFIG_WS2812_PWM=y
CONFIG_WS2812_PWM_STM32=y
CONFIG_DMA=y
CONFIG_DMA_STM32=y

# HDC2010 temperature/humidity sensor (uses HDC20xx driver)
#CONFIG_SENSOR=y
#CONFIG_HDC20XX=y
