# Enable GPIO Expander support
CONFIG_GPIO_TCA6424A=y

# Enable EEPROM support
CONFIG_EEPROM=y
CONFIG_EEPROM_AT24=y

# TCA9548A multiplexer init ordering.
CONFIG_I2C_TCA954X_ROOT_INIT_PRIO=60
CONFIG_I2C_TCA954X_CHANNEL_INIT_PRIO=61

# HDC2010 temperature/humidity sensor (uses HDC20xx driver)
#CONFIG_SENSOR=y
#CONFIG_HDC20XX=y